New test groups
luxteam/jobs_test_usdblender pull request #6
Opened 2021-07-23 08:28 UTC by NISHIY-EKSDEE

## JIRA TICKET
https://luxproject.luxoft.com/jira/browse/STVCIS-2361
## EFFECT OF CHANGE
Extended Smoke
New groups: 
- MaterialX_Uber
- MaterialX_Standart_Surface
- Physical_Lights
- Render_Quality
- Render_Mode
- Camera
- Image _Size
## NOTES FOR REVIEWERS
Currently cases have huge render time. Timeouts not optimized yet
[Test Cases](https://docs.google.com/spreadsheets/d/1ozZ_MRu7kijgGcWbSemxJA6efTYqOxwhXMhtCntFW8w/edit#gid=0)
## REPORTS
[MX_Uber, MX_SS](https://rpr.cis.luxoft.com/job/DevJobs/job/DevBlenderUSDHydraPluginManual/4/)
[Physical Lights, Camera (RQ had little timeout, RM had a mistake in functions)](https://rpr.cis.luxoft.com/job/DevJobs/job/DevBlenderUSDHydraPluginManual/9/)
[Render Quality](https://rpr.cis.luxoft.com/job/DevJobs/job/DevBlenderUSDHydraPluginManual/10/)
[Smoke](https://rpr.cis.luxoft.com/job/DevJobs/job/DevBlenderUSDHydraPluginManual/11/)
[Render Mode](https://rpr.cis.luxoft.com/job/DevJobs/job/DevBlenderUSDHydraPluginManual/13/)
[Image Size](https://rpr.cis.luxoft.com/job/DevJobs/job/DevBlenderUSDHydraPluginManual/15/)
[Regression with new groups](https://rpr.cis.luxoft.com/job/DevJobs/job/DevBlenderUSDHydraPluginManual/16/)

2021-07-29 12:00 UTC, Piromancer commented
Мы в процессе разбора результатов
Можно прикрепить отчет с полным прогоном к ПРу
https://rpr.cis.luxoft.com/job/DevJobs/job/DevBlenderUSDHydraPluginManual/18/

2021-07-29 12:40 UTC, Piromancer requested changes
Такие замечания:
1. https://rpr.cis.luxoft.com/job/DevJobs/job/DevBlenderUSDHydraPluginManual/18/Test_20Report_20RPR/AMD_RX5700XT-Windows-Physical_Lights/Results/BlenderUSDHydra/Physical_Lights/render_tool_logs/USD_PL_004.log
Error "'PointLight' object has no attribute 'rpr'" with string "set_value(light_data.rpr, 'intensity', 5000)"
2. Для сокращения времени (и в целом это необходимо) нужно внедрить поддержку параметра Samples. По умолчанию давайте поставим 50. Это тот же параметр что и в USD_RM_011-014. И Threshold тоже можно поставить 0.05 по умолчанию, но сделать так чтобы можно было задать. Так время рендеринга сразу раза в 4 сократиться
![image](https://user-images.githubusercontent.com/44932328/127492539-4e8047c5-677e-42f2-bcee-63cab9fc5c37.png)
3. https://rpr.cis.luxoft.com/job/DevJobs/job/DevBlenderUSDHydraPluginManual/18/Test_20Report_20RPR/AMD_RX5700XT-Windows-Smoke/Results/BlenderUSDHydra/Smoke/render_tool_logs/USD_SM_006.log
Error "'bpy_prop_collection[key]: key "MX_Material" not found'" with string "bpy.data.materials['Material'].hdusd.mx_node_tree = bpy.data.node_groups['MX_Material']"
4. Что произошло с NVIDIA? https://rpr.cis.luxoft.com/job/DevJobs/job/DevBlenderUSDHydraPluginManual/18/Test_20Report_20GL/

2021-08-02 08:15 UTC, NISHIY-EKSDEE commented
1. Исправил.
https://rpr.cis.luxoft.com/job/DevJobs/job/DevBlenderUSDHydraPluginManual/20/
2. Добавил, рендер тайм сильно уменьшился
https://rpr.cis.luxoft.com/job/DevJobs/job/DevBlenderUSDHydraPluginManual/21/
3. На некоторых машинах лежит старая сцена с простым кубом и таким же названием. Постепенно везде проверю и поменяю
4. Не построился кэш, в новом прогоне не воспроизвелось https://rpruser:cis.report@cis.nas.luxoft.com/DevJobs/DevBlenderUSDHydraPluginManual/21/Test_Report_GL/summary_report.html

2021-08-02 09:53 UTC, Piromancer commented
Спасибо, запустил фул проверить таймауты
https://rpr.cis.luxoft.com/job/DevJobs/job/DevBlenderUSDHydraPluginManual/24/

2021-08-03 09:32 UTC, Piromancer requested changes
Есть еще ошибки в Physical_Lights
https://rpruser:cis.report@cis.nas.luxoft.com/DevJobs/DevBlenderUSDHydraPluginManual/24/Test_Report_RPR/AMD_WX9100-Windows-Physical_Lights/Results/BlenderUSDHydra/Physical_Lights/render_tool_logs/USD_PL_132.log
https://rpruser:cis.report@cis.nas.luxoft.com/DevJobs/DevBlenderUSDHydraPluginManual/24/Test_Report_RPR/AMD_WX9100-Windows-Physical_Lights/Results/BlenderUSDHydra/Physical_Lights/render_tool_logs/USD_PL_116.log

Все нужные кейсы я проскипал таймауты где-то увеличил. Сейчас запущу фул снова

2021-08-03 09:35 UTC, Piromancer commented
И давай попробуем сделать что-то со старым кубом. Я не совсем, если честно, понял как старая сцена может ломать тест. Если сцена автоматически не заменяется, то это проблема. Надо сделать, чтобы заменялась

2021-08-03 09:48 UTC, NISHIY-EKSDEE commented
> Есть еще ошибки в Physical_Lights
> https://rpruser:cis.report@cis.nas.luxoft.com/DevJobs/DevBlenderUSDHydraPluginManual/24/Test_Report_RPR/AMD_WX9100-Windows-Physical_Lights/Results/BlenderUSDHydra/Physical_Lights/render_tool_logs/USD_PL_132.log
> https://rpruser:cis.report@cis.nas.luxoft.com/DevJobs/DevBlenderUSDHydraPluginManual/24/Test_Report_RPR/AMD_WX9100-Windows-Physical_Lights/Results/BlenderUSDHydra/Physical_Lights/render_tool_logs/USD_PL_116.log

Насколько я понимаю, этот функционал еще не поддерживается. Там нет таких параметров

Старая сцена автоматически заменяется, я ее переименовал, ибо нигде не используется. В ней не было MX_Material нод группы, что вызывало ошибку. В этом прогоне уже новая сцена

2021-08-05 11:42 UTC, Piromancer approved these changes
Ждем обновления бейзлайнов и можно мерджить

2021-08-06 12:00 UTC, merged