Avk/cloud
luxteam/jobs_test_usdblender pull request #79
Opened 2022-06-23 19:25 UTC by Flame0n

### Jira Ticket
https://luxproject.luxoft.com/jira/browse/STVCIS-3018

### Jenkins Builds
-- Denis
https://rpr.cis.luxoft.com/job/USD-BlenderPlugin-Manual/871/ - cloud group all machines
-- Ilya
https://rpr.cis.luxoft.com/job/USD-BlenderPlugin-Manual/872/ - regression for check new logic didn't broke older cases
https://rpr.cis.luxoft.com/job/USD-BlenderPlugin-Manual/873/ - full for check new logic didn't broke older cases

2022-06-27 05:56 UTC, Speedwag00n requested changes

2022-06-27 05:56 UTC, Speedwag00n commented on jobs/Scripts/base_functions.py
> +    node_tree.links.new(world_output.inputs['Surface'], background_node.outputs['Background'])
Специфичные для группы функции нужно выносить в файл функции
Например:
https://github.com/luxteam/jobs_test_usdblender/blob/master/jobs/Scripts/extensions/Camera.py

2022-06-30 22:07 UTC, Flame0n commented
@Piromancer 
1. Здесь конкретнее, потому что я вижу кучу анскипнутых кейсов, которые отработали(не факт, что правильно). Плюсом те кейсы, которые не были скипнуты в этих делегатах ранее - имеют такие же результаты, что и в мастере.
2. Здесь 20 убунтка с 2070 не отработала по причине того, что в тот момент драйвер отлетел в системе.
3. Опять же я вижу 2 еррора в RPR на 9100, которые воспроизводятся и требуют скипа, 2070 можно не учитывать, по тому, что описал выше и по GL с Hybrid, тоже описано выше. Артуру напишу насчет ошибок и тикетов на них.
4. Учту

2022-07-01 11:59 UTC, Flame0n commented
@Piromancer 
https://amdrender.atlassian.net/browse/BLEN-159 - Артур завел тикет, я не знаю, что в нём, тк нет доступа.
Добавил скипы на все ошибки в Гибриде. ГЛ Артур сказал оставить как есть.

2022-07-01 12:13 UTC, Piromancer approved these changes

2022-07-01 12:15 UTC, Speedwag00n approved these changes

2022-07-01 12:15 UTC, merged